// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lslvhmkspdhlqrlciwmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzbHZobWtzcGRobHFybGNpd21mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTQ2OTEsImV4cCI6MjA3MjA3MDY5MX0.mWCeIizkPsh2xlAPfF11vulPw899cGOAkkczqF-Cey0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});